### ISSUE TITLE
Sync Data button should be disabled if there is not and data to sync.

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#193]

**Comment by sethvincent** [comment]
I'm not sure if we should disable it. It's a two-way sync, and right now it's the main way to pull in observations from other team members. It's not at all clear that's what it does though, because its placement kinda implies that it is only transferring that user's data. The only other situation where observations are synced is when the user imports a survey.

**Comment by felskia** [comment]
@sethvincent Ah, gotcha... ok, I'll relabel this.

**Comment by noffle** [comment]
It is also technically challenging to determine if there are new changes on either side of a sync before doing the sync. We'd need to make a fake copy of our data, secretly *do* the sync in the background, and then compare the newly-sync'd database to the local one to check for changes.
