### ISSUE TITLE
Add class so that state can change when link is pressed

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-collection#200]
For surveys that are selected can we add a class here so that I can change the style? 
<img width="248" alt="screen shot 2017-08-22 at 8 29 25 pm" src="https://user-images.githubusercontent.com/5421566/29593523-d556feb4-8778-11e7-806c-186cb18c1432.png">

**Comment by sethvincent** [comment]
Couldn't quite add a class, but added a thing a little while back that does this:

- checks previously imported surveys and compares that with the remote list
- if a survey has already been imported, it shows a little `✔ Synced` message underneath the survey name. That should propably say imported, rather than synced. Or remove that text and change the styling in some way.
- the above applies to a survey that a user taps to import as well. As soon as the data transfer is complete the `✔ Synced` message appears.

That stuff happens here: https://github.com/osmlab/field-data-collection/blob/master/app/screens/Account/RemoteSurveyList.js#L39-L56
